# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"run_shell_installs": "01_dialog_system.ipynb",
         "replacement_f": "01_dialog_system.ipynb",
         "gen_faq_config_file": "01_dialog_system.ipynb",
         "load_qa_models": "01_dialog_system.ipynb",
         "select_squad_responses": "01_dialog_system.ipynb",
         "select_faq_responses": "01_dialog_system.ipynb",
         "format_responses": "01_dialog_system.ipynb",
         "get_responses": "01_dialog_system.ipynb",
         "get_input": "01_dialog_system.ipynb",
         "new_answer": "01_dialog_system.ipynb",
         "question_response": "01_dialog_system.ipynb",
         "dialog_system": "01_dialog_system.ipynb"}

modules = ["dialog_system.py"]

doc_url = "https://kikejimenez.github.io/let_me_answer_for_you/"

git_url = "https://github.com/kikejimenez/let_me_answer_for_you/tree/master/"

def custom_doc_links(name): return None
