# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"change_log_config": "01_settings.ipynb",
         "run_shell_installs": "01_settings.ipynb",
         "action_over_list_f": "01_settings.ipynb",
         "replacement_f": "01_settings.ipynb",
         "updates_faq_config_file": "01_settings.ipynb",
         "select_faq_responses": "01_settings.ipynb",
         "select_squad_responses": "01_settings.ipynb",
         "load_qa_models": "01_settings.ipynb",
         "get_responses": "01_settings.ipynb",
         "format_responses": "01_settings.ipynb",
         "get_input": "01_settings.ipynb",
         "question_response": "01_settings.ipynb",
         "new_question_answer": "01_settings.ipynb",
         "new_context": "01_settings.ipynb",
         "set_minimal_faq_questions": "01_settings.ipynb",
         "set_minimal_contexts": "01_settings.ipynb",
         "set_data_dict": "01_settings.ipynb",
         "load_and_prepare_data": "01_settings.ipynb",
         "DialogSystem": "02_dialog_system.ipynb",
         "ChatBot": "03_chatbot.ipynb"}

modules = ["settings.py",
           "dialog_system.py",
           "chatbot.py"]

doc_url = "https://kikejimenez.github.io/let_me_answer_for_you/"

git_url = "https://github.com/kikejimenez/let_me_answer_for_you/tree/master/"

def custom_doc_links(name): return None
